version: '3.8'
services: 
  vprodb:
    image: vprofiledb
    container_name: vprodb
    build: 
      context: ./Docker-files/db
      dockerfile: Dockerfile
    volumes:
      - ./vpdbdata:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: accounts

  vprocache01:
    image: memcached
    ports:
      - 11211:11211

  vpromq01:
    image: rabbitmq
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: vprofileapp
    container_name: vproapp
    build:
      context: ./Docker-files/app
      dockerfile: Dockerfile
    volumes:
      - ./vpappdata:/usr/tomcat/webapps
    ports:
      - 8080:8080

  vproweb:
    image: vprofileweb
    container_name: vproweb
    build:
      context: ./Docker-files/web
      dockerfile: Dockerfile
    ports:
      - 80:80

volumes:
  vpappdata: {}
  vpdbdata: {}